### PR TITLE
`Bugfix/Enhancement` Fixed version control related bugs

### PR DESCRIPTION
**Pull request by Kroko-fant**
### Motivation and Context

Artemis has changed DTOs from URL to URI which broke some plugin code that depends on the repository URLs.
https://github.com/ls1intum/Artemis/pull/7838

Furthermore Artemis has changed the version-control system away from Bitbucket. Orion however still referenced the TUM bitbucket

This pr fixes:
https://github.com/ls1intum/Orion/issues/104
https://github.com/ls1intum/Orion/issues/105
https://github.com/ls1intum/Orion/issues/106

### Steps for Testing

1. Install the release as described in [the readme](https://github.com/ls1intum/Orion/blob/main/README.md#testing-of-pull-requests)
2. Open an exercise in Orion
2.1. As a student
2.2. As a tutor
2.3. As an instructor
-> verify that the cloning process does not throw errors as described in the linked issues
3. Open the settings UI and verify that the new field is present
4. ...

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

grafik
Updated Settings UI

### CODE REVIEW

**Review by Jan-Thurner — APPROVED** [review]
Tested as Student, Tutor, and Instructor and worked well. No of the issues occurred. The settings page looks good as well.

**Review by b-fein — COMMENTED** [review]
This may only be a partial fix for #104. The error message is still

> Id of the opened submission and the loaded Artemis page do not match, loading of feedback aborted. Make sure to open the correct submission in Orion.

**Comment by Kroko-fant** [comment]
> This may only be a partial fix for #104. The error message is still
> 
> > Id of the opened submission and the loaded Artemis page do not match, loading of feedback aborted. Make sure to open the correct submission in Orion.



> This may only be a partial fix for #104. The error message is still
> 
> > Id of the opened submission and the loaded Artemis page do not match, loading of feedback aborted. Make sure to open the correct submission in Orion.

I tried replicating this issue and couldn't get it replicated. Does setting up the entire correction repository fix the issue?

**Comment by b-fein** [comment]
> Does setting up the entire correction repository fix the issue?

What does setting up the entire correction repository mean? Do I have to do something else as an instructor before I can start the assessment of student submissions?

**Review by pzdr7 — APPROVED** [review]
Tested:

- New settings field is present
- Student: Open in IDE; submit works
- Tutor: Assess in IDE via assessment dashboard works
- Instructor: Edit exercise in IDE works
- Instructor: Assess via scores page works

I was unable to reproduce the bug in #104.

**Review by basak-akan — APPROVED** [review]
Tested locally works well, also code lgtm

**Pull request merged**
