### PR TITLE
Update dependencies to 2021.1

### LINKED ISSUE #40: Open in IntelliJ does not work (as Editor)
### Describe the bug

The _Open in IntelliJ_ functionality does not work.

#### To Reproduce

1. Start Orion with gradle _runIDE_
2. Log in as editor in a course
3. Try to start working on this exercise from the student view
4. _Open in IntelliJ_ does not work
5. See that a JsonSyntaxException is thrown

#### Expected behavior

Clicking _Open in IntellJ_ should open the project in the IDE

#### Screenshots

Button does not work:
ReviewPR39OrionUpdateDependencies

### Environment

<details><pre>
 - OS: Windows 10
 - IntelliJ 2021.1
 - Browser Chrome 90.0.4430.93
 - Orion Version: 1.1.1
</pre></details>

#### Output in IntelliJ

<details><pre>
Exception in thread "Thread-13730" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 3960 path $.categories[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at de.tum.www1.orion.connector.ide.exercise.OrionExerciseConnector.importParticipation(OrionExerciseConnector.kt:76)
	at de.tum.www1.orion.connector.ide.exercise.OrionExerciseConnector$initializeHandlers$1.onQuery(OrionExerciseConnector.kt:43)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 3960 path $.categories[0]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 6 more
</pre></details>

### PR DESCRIPTION
**Pull request by MDK5**
### Description
Updates all dependencies to IntelliJ 2021.1.1. Python (Python for IntelliJ Ultimate) had to be replaced with PythonCore (Python for Intellij Community) to fix issues with dependencies; no functionality seems to be affected by this.

Also fixes #40.

### Steps for Testing
Version May 6: [orion.zip](https://github.com/ls1intum/Orion/files/6436333/orion.zip)

1. Install the release as described in [the readme](https://github.com/ls1intum/Orion/blob/master/README.md#installation-of-a-release-zip)
2. Check if all features still work (start exercise, submit changes, recieve test results)

Please add which IntelliJ version you tested with (Ultimate (IU) or Community (IC))

### CODE REVIEW

**Review by florian-glombik — APPROVED** [review]
Tested it locally, I have had an issue https://github.com/ls1intum/Orion/issues/40 but it does not seem to be related to this PR since it also occurs on the develop branch.

**Review by ivanchimeno — APPROVED** [review]
Works for me too

**Comment by ivanchimeno** [comment]
> Tested it locally, I have had an issue #40 but it does not seem to be related to this PR since it also occurs on the develop branch.

Interesting, for me it worked

**Review by lschlesinger — APPROVED** [review]
I encountered the same issues as @KiraNickel and @florian-glombik for both versions, 2020.2 and 2021.1 -> issue #40 but probably not related to your PR!

**Review by florian-glombik — APPROVED** [review]
Tested it locally (linux machine) with IntelliJ 2021.1 and https://github.com/ls1intum/Orion/issues/40 is resolved :+1:

**Review by FuchsDominik — APPROVED** [review]
Can approve that the usual workflow behaves as usual and the #40 bug is fixed

**Review by KiraNickel — APPROVED** [review]
Tested locally on Windows 10 machine with Intellij 2021.1 Ultimate.
Bug #40 is fixed for me too and the ususal workflow is working fine 👍🏼 😀

**Pull request merged**
