### PR TITLE
Studentreview

### PR DESCRIPTION
**Pull request by Kroko-fant**
### Motivation and Context
Students should be able to review their code in Orion. Tutors already use Orion put inline Feedback to student code and Orion should be able to display that feedback.

### Description
This PR gives a basic view for feedback so students can see inline feedback in their IDE and don't have to look for referenced lines in the feedback comments. After the deadline has passed, Students can click again on button to get a programming excercise in their Jetbrains IDE and Orion will open a different editor view where it shows inline feedback. This can help students to review their code better.

### Steps for Testing

1. Install the release as described in [the readme](https://github.com/ls1intum/Orion/blob/main/README.md#testing-of-pull-requests)
2. Open an exercise in Orion
3. Submit some changes as a student
4. Wait for the deadline to be passed
5. Wait for a tutor to correct the exercise.
6. Click Reload Feedback button
7. View Feedback

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

grafik

### CODE REVIEW

**Review by pal03377 — COMMENTED** [review]
Tested in testing session, there was an issue with some translation string and we didn't yet see feedback

**Comment by Strohgelaender** [comment]
Please note that https://github.com/ls1intum/Artemis/pull/7015 will change how test cases work in Artemis and will probably break the current implementation.

**Review by MaximilianAnzinger — APPROVED** [review]
Tested in testing session

**Review by laurenzfb — APPROVED** [review]
tested in testing session

**Review by florian-glombik — APPROVED** [review]
The feedback was displayed within the IntelliJ project 

There are some issues that can be fixed in a follow-up PR
* The Feedback is not loaded properly when the files are still opened
proposed solution: display a message to close the files/force overwrite the files
* Orion does not auto-refresh if e.g. the assessment type of the exercise is changed _(exercise needs to be )_

**Pull request merged**
