### PR TITLE
[feature] add return button

### LINKED ISSUE #33: Allow users to navigate back to Artemis from external webcontent
This was the result of a discussion we had way back, where we decided to not let users break out of the "Artemis space" since we can't really guarantee what will happen as only the usage with the Artemis website is tested. 
Let's also say a teaching assistant links a code example and the student clicks on it. He is now outside of our domain and has no obvious way of going back, apart from re-opening the IDE/reloading in the settings/left-click context menu.

Now, for this specific case, we absolutely should allow users to use external login mechanisms. What I wanted to have and would be my favorite solution, is to remove the pop-up completely and then have a button above the browser (so an IDE-native button on top off the tool window next to the default ones), which always brings you back to the Artemis homepage if you have any problems whatsoever. An alternative would be to have a prominent button overlayed, having the same functionality, as soon as we detect a user leaving the domain. 
No matter what, removing the current blocking of external domains should be the first step @nutatuna .

_Originally posted by @ungaralex in https://github.com/ls1intum/Orion/issues/30#issuecomment-728347346_

### PR DESCRIPTION
**Pull request by MDK5**
### Motivation and Context
Resolves #33

### Description
Adds a button on the toolbar that allows to always return to the configured Artemis Base URL. Also switches to a more reliable way of overwriting the user agent.

### Steps for Testing
1. Install the release as described in [the readme](https://github.com/ls1intum/Orion/blob/master/README.md#testing-of-pull-requests)
2. Press the newly created button under various circumstances
3. Make sure after returning the submit button is available
4. Be aware #49 is fixed but not yet deployed

### Screenshots
button

### CODE REVIEW

**Review by JuliusKreutz — CHANGES_REQUESTED** [review]
When in exercise, pressing the return button overrides the submit button. So you can no longer submit the exercise!

**Review by JuliusKreutz — APPROVED** [review]
Submit button doesn't get overwritten anymore.
Code LGTM!

**Review by lschlesinger — APPROVED** [review]
Besides the known issues, that you told us about in the testing session the return button works as expected!

**Review by tobiasjungmann — APPROVED** [review]
The return button worked as described, other buttons had known issues.

**Comment by krusche** [comment]
I don't like the placement of the button. Ideally it is placed in the toolbar just above the current place.
Please try to improve this is in a follow-up

**Pull request merged**
