### PR TITLE
`Feature` Highlight Todos in Java Exercises

### PR DESCRIPTION
**Pull request by Kroko-fant**
### Motivation and Context
Orion should be able to highlight todos in the template code even if the student deleted them.

### Description
the assessment mode of Orion now provides the ability to view todos as comments inside of the assessment editor.

### Steps for Testing
1. Install Orion and start an exercise in **assessment mode**.
2. Open a student file in the assessment editor and verify that the todos are mapped correctly.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Newly added Files by the student do not show any todos
grafik

Todos can stick to the File, Class and Method
grafik
grafik

### CODE REVIEW

**Review by jakubriegel — APPROVED** [review]
Demonstrated on a ts. Works fine

**Review by jakubriegel — APPROVED** [review]
Demonstrated on a ts. Works fine

**Review by MaximilianAnzinger — APPROVED** [review]
Tested during testing session, seems to work quite well :+1:

**Review by Jan-Thurner — APPROVED** [review]
Works like a charm

**Pull request merged**
